database:
  host: localhost
  port: 5432
  dialect: postgres
  user: postgres
  dbname: im-db
  password: password
  gormMaxIdleConn: 20
  gormMaxOpenConn: 300
  gormMaxConnLifetimeHour: 1
  sslmode: disable
  schema: im.

app:
  host: main-imd.technofusion.az
  port: 8080

jwt:
  secretKey: 9bd82804-970d-44d6-9bc9-f65079ab10dd
  publicKey: secret
  privateKey: secret
  saltKey: salt-key
  accessTokenExpire: 2592000

swagger:
  host:
  scheme:
